name: csm_foundation_services
description: A csm foundation package to services implementations.
version: 6.0.0
publish_to: none
repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

dependencies:
  http: ^1.2.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
